<?php

/**
 * @file
 * Show entity.
 */

/**
 * Implements hook_entity_info().
 *
 * This is the fundamental description of the entity.
 *
 * It provides a single entity with a single bundle and without revision
 * support.
 */
function show_entity_info() {
  $info['show'] = array(
    // A human readable label to identify our entity.
    'label' => t('Show Entity'),

    // The controller for our Entity, extending the Drupal core controller.
    'controller class' => 'ShowController',

    // The table for this entity defined in hook_schema()
    'base table' => 'show',

    // Returns the uri elements of an entity.
    'uri callback' => 'show_uri',

    // IF fieldable == FALSE, we can't attach fields.
    'fieldable' => TRUE,

    // entity_keys tells the controller what database fields are used for key
    // functions. It is not required if we don't have bundles or revisions.
    // Here we do not support a revision, so that entity key is omitted.
    'entity keys' => array(
      // The 'id' is the unique id.
      'id' => 'id' ,
      // Bundle will be determined by the 'bundle_type' field.
      'bundle' => 'bundle_type',
    ),
    'bundle keys' => array(
      'bundle' => 'bundle_type',
    ),

    // FALSE disables caching. Caching functionality is handled by Drupal core.
    'static cache' => TRUE,

    // Bundles are alternative groups of fields or configuration associated with
    // a base entity type.
    'bundles' => array(
      'default' => array(
        'label' => 'Default bundle',
        // 'admin' key is used by the Field UI to provide field and
        // display UI pages.
        'admin' => array(
          'path' => 'admin/structure/show/manage',
          'access arguments' => array('administer show entities'),
        ),
      ),
    ),
    // View modes allow entities to be displayed differently based on context.
    // As a demonstration we'll support "Full", but we could have and support
    // multiple display modes.
    'view modes' => array(
      'full' => array(
        'label' => t('Full'),
        'custom settings' => FALSE,
      ),
    ),
  );

  return $info;
}

/**
 * Fetch a show object.
 *
 * This function ends up being a shim between the menu system and
 * show_load_multiple().
 *
 * This function gets its name from the menu system's wildcard
 * naming conventions. For example, /path/%wildcard would end
 * up calling wildcard_load(%wildcard value). In our case defining
 * the path: show/%show in hook_menu() tells Drupal to call show_load().
 *
 * @param int $id
 *   Integer specifying the show entity id.
 * @param bool $reset
 *   A boolean indicating that the internal cache should be reset.
 *
 * @return object
 *   A fully-loaded $show object or FALSE if it cannot be loaded.
 *
 * @see show_load_multiple()
 * @see show_menu()
 */
function show_load($id = NULL, $reset = FALSE) {
  $ids = (isset($id) ? array($id) : array());
  $show = show_load_multiple($ids, array(), $reset);
  return $show ? reset($show) : FALSE;
}

/**
 * Loads multiple show entities.
 *
 * We only need to pass this request along to entity_load(), which
 * will in turn call the load() method of our entity controller class.
 */
function show_load_multiple($ids = FALSE, $conditions = array(), $reset = FALSE) {
  return entity_load('show', $ids, $conditions, $reset);
}

/**
 * Implements the uri callback.
 */
function show_uri($show) {
  return array(
    'path' => 'show/' . $show->id,
  );
}

/**
 * Implements hook_menu().
 */
function show_menu() {
  // This provides a place for Field API to hang its own
  // interface and has to be the same as what was defined
  // in show  _entity_info() above.
  $items['admin/structure/show/manage'] = array(
    'title' => 'Administer show entity type',
    'page callback' => 'show_list_entities',
    'access arguments' => array('administer show entities'),
  );

  // Add show entities.
  $items['admin/structure/show/manage/add'] = array(
    'title' => 'Add a Show entity',
    'page callback' => 'show_add',
    'access arguments' => array('create show entities'),
    'type' => MENU_LOCAL_ACTION,
  );

  // List of all show entities.
  $items['admin/structure/show/manage/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  // The page to view our entities - needs to follow what
  // is defined in show_uri and will use show_load to retrieve
  // the necessary entity info.
  $items['show/%show'] = array(
    'title callback' => 'show_title',
    'title arguments' => array(1),
    'page callback' => 'show_view',
    'page arguments' => array(1),
    'access arguments' => array('view any show entity'),
  );

  // 'View' tab for an individual entity page.
  $items['show/%show/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  // 'Edit' tab for an individual entity page.
  $items['show/%show/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('show_form', 3),
    'access arguments' => array('edit any show entity'),
    'type' => MENU_LOCAL_TASK,
  );

  // Add show entities.
  $items['show/add'] = array(
    'title' => 'Add a Show entity',
    'page callback' => 'show_add',
    'access arguments' => array('create show entities'),
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function show_permission() {
  $permissions = array(
    'administer show entities' => array(
      'title' => t('Administer show entities'),
    ),
    'view any show entity' => array(
      'title' => t('View any Show entity'),
    ),
    'edit any show entity' => array(
      'title' => t('Edit any Show entity'),
    ),
    'create show entities' => array(
      'title' => t('Create Show Entities'),
    ),
  );
  return $permissions;
}

/**
 * Callback for a page title when this entity is displayed.
 */
function show_title($entity) {
  return t('Show (description=@description)', array('@description' => $entity->description));
}

/**
 * Menu callback to display an entity.
 *
 * As we load the entity for display, we're responsible for invoking a number
 * of hooks in their proper order.
 *
 * @see hook_entity_prepare_view()
 * @see hook_entity_view()
 * @see hook_entity_view_alter()
 */
function show_view($entity, $view_mode = 'full') {
  // Our entity type, for convenience.
  $entity_type = 'show';
  // Start setting up the content.
  $entity->content = array(
    '#view_mode' => $view_mode,
  );
  // Build fields content - this is where the Field API really comes in to play.
  // The task has very little code here because it all gets taken care of by
  // field module.
  // field_attach_prepare_view() lets the fields load any data they need
  // before viewing.
  field_attach_prepare_view($entity_type, array($entity->id => $entity),
    $view_mode);
  // We call entity_prepare_view() so it can invoke hook_entity_prepare_view()
  // for us.
  entity_prepare_view($entity_type, array($entity->id => $entity));
  // Now field_attach_view() generates the content for the fields.
  $entity->content += field_attach_view($entity_type, $entity, $view_mode);

  // OK, Field API done, now we can set up some of our own data.
  $entity->content['created'] = array(
    '#type' => 'item',
    '#title' => t('Created date'),
    '#markup' => format_date($entity->created),
  );
  $entity->content['description'] = array(
    '#type' => 'item',
    '#title' => t('Item Description'),
    '#markup' => $entity->description,
  );

  // Now to invoke some hooks. We need the language code for
  // hook_entity_view(), so let's get that.
  global $language;
  $langcode = $language->language;
  // And now invoke hook_entity_view().
  module_invoke_all('entity_view', $entity, $entity_type, $view_mode,
    $langcode);
  // Now invoke hook_entity_view_alter().
  drupal_alter(array('show_view', 'entity_view'),
    $entity->content, $entity_type);

  // And finally return the content.
  return $entity->content;
}

/**
 * Implements hook_field_extra_fields().
 *
 * This exposes the "extra fields" (usually properties that can be configured
 * as if they were fields) of the entity as pseudo-fields
 * so that they get handled by the Entity and Field core functionality.
 * Node titles get treated in a similar manner.
 */
function show_field_extra_fields() {
  $form_elements['description'] = array(
    'label' => t('Item Description'),
    'description' => t('Item Description (an extra form field)'),
    'weight' => -5,
  );
  $display_elements['created'] = array(
    'label' => t('Creation date'),
    'description' => t('Creation date (an extra display field)'),
    'weight' => 0,
  );
  $display_elements['description'] = array(
    'label' => t('Item Description'),
    'description' => t('Just like title, but trying to point out that it is a separate property'),
    'weight' => 0,
  );

  // Since we have only one bundle type, we'll just provide the extra_fields
  // for it here.
  $extra_fields['show']['default']['form'] = $form_elements;
  $extra_fields['show']['default']['display'] = $display_elements;

  return $extra_fields;
}

/**
 * Provides a wrapper on the edit form to add a new entity.
 */
function show_add() {
  // Create a show entity structure to be used and passed to the validation
  // and submission functions.
  $entity = entity_get_controller('show')->create();
  return drupal_get_form('show_form', $entity);
}

/**
 * Form function to create an show entity.
 *
 * The pattern is:
 * - Set up the form for the data that is specific to your
 *   entity: the columns of your base table.
 * - Call on the Field API to pull in the form elements
 *   for fields attached to the entity.
 */
function show_form($form, &$form_state, $entity) {
  $form['description'] = array(
    '#type' => 'textfield',
    '#title' => t('Item Description'),
    '#required' => TRUE,
    '#default_value' => $entity->description,
  );

  $form['entity'] = array(
    '#type' => 'value',
    '#value' => $entity,
  );

  field_attach_form('show', $entity, $form, $form_state);

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
    '#weight' => 100,
  );
  $form['delete'] = array(
    '#type' => 'submit',
    '#value' => t('Delete'),
    '#submit' => array('show_edit_delete'),
    '#weight' => 200,
  );

  return $form;
}


/**
 * Validation handler for show_add_form form.
 *
 * We pass things straight through to the Field API to handle validation
 * of the attached fields.
 */
function show_form_validate($form, &$form_state) {
  field_attach_form_validate('show', $form_state['values']['entity'], $form, $form_state);
}


/**
 * Form submit handler: Submits show_add_form information.
 */
function show_form_submit($form, &$form_state) {
  $entity = $form_state['values']['entity'];
  $entity->description = $form_state['values']['description'];
  field_attach_submit('show', $entity, $form, $form_state);
  $entity = show_save($entity);
  $form_state['redirect'] = 'show/' . $entity->id;
}

/**
 * Form deletion handler.
 *
 * @todo: 'Are you sure?' message.
 */
function show_edit_delete($form, &$form_state) {
  $entity = $form_state['values']['entity'];
  show_delete($entity);
  drupal_set_message(t('The entity %description (ID %id) has been deleted',
    array('%description' => $entity->description, '%id' => $entity->id))
  );
  $form_state['redirect'] = '';
}

/**
 * We save the entity by calling the controller.
 */
function show_save(&$entity) {
  return entity_get_controller('show')->save($entity);
}

/**
 * Use the controller to delete the entity.
 */
function show_delete($entity) {
  entity_get_controller('show')->delete($entity);
}

/**
 * ShowControllerInterface definition.
 *
 * We create an interface here because anyone could come along and
 * use hook_entity_info_alter() to change our controller class.
 * We want to let them know what methods our class needs in order
 * to function with the rest of the module, so here's a handy list.
 *
 * @see hook_entity_info_alter()
 */
interface ShowControllerInterface
  extends DrupalEntityControllerInterface {

  /**
   * Create an entity.
   */
  public function create();

  /**
   * Save an entity.
   *
   * @param object $entity
   *   The entity to save.
   */
  public function save($entity);

  /**
   * Delete an entity.
   *
   * @param object $entity
   *   The entity to delete.
   */
  public function delete($entity);

}

/**
 * ShowController extends DrupalDefaultEntityController.
 *
 * Our subclass of DrupalDefaultEntityController lets us add a few
 * important create, update, and delete methods.
 */
class ShowController
  extends DrupalDefaultEntityController
  implements ShowControllerInterface {

  /**
   * Create and return a new show entity.
   */
  public function create() {
    $entity = new stdClass();
    $entity->type = 'show';
    $entity->id = 0;
    $entity->bundle_type = 'default';
    $entity->description = '';
    return $entity;
  }

  /**
   * Saves the custom fields using drupal_write_record().
   */
  public function save($entity) {
    // If our entity has no id, then we need to give it a time of creation.
    if (empty($entity->id)) {
      $entity->created = time();
    }
    // Invoke hook_entity_presave().
    module_invoke_all('entity_presave', $entity, 'show');
    // The 'primary_keys' argument determines whether this will be an insert
    // or an update. So if the entity already has an ID, we'll specify
    // id as the key.
    $primary_keys = $entity->id ? 'id' : array();
    // Write out the entity record.
    drupal_write_record('show', $entity, $primary_keys);
    // We're going to invoke either hook_entity_update() or
    // hook_entity_insert(), depending on whether or not this is a
    // new entity. We'll just store the name of hook_entity_insert()
    // and change it if we need to.
    $invocation = 'entity_insert';
    // Now we need to either insert or update the fields which are
    // attached to this entity. We use the same primary_keys logic
    // to determine whether to update or insert, and which hook we
    // need to invoke.
    if (empty($primary_keys)) {
      field_attach_insert('show', $entity);
    }
    else {
      field_attach_update('show', $entity);
      $invocation = 'entity_update';
    }
    // Invoke either hook_entity_update() or hook_entity_insert().
    module_invoke_all($invocation, $entity, 'show');
    return $entity;
  }

  /**
   * Delete a single entity.
   *
   * Really a convenience function for deleteMultiple().
   */
  public function delete($entity) {
    $this->deleteMultiple(array($entity));
  }

  /**
   * Delete one or more show entities.
   *
   * Deletion is unfortunately not supported in the base
   * DrupalDefaultEntityController class.
   *
   * @param array $entities
   *   An array of entity IDs or a single numeric ID.
   *
   * @throws Exception
   */
  public function deleteMultiple($entities) {
    $ids = array();
    if (!empty($entities)) {
      $transaction = db_transaction();
      try {
        foreach ($entities as $entity) {
          // Invoke hook_entity_delete().
          module_invoke_all('entity_delete', $entity, 'show');
          field_attach_delete('show', $entity);
          $ids[] = $entity->id;
        }
        db_delete('show')
          ->condition('id', $ids, 'IN')
          ->execute();
      }
      catch (Exception $e) {
        $transaction->rollback();
        watchdog_exception('show', $e);
        throw $e;
      }
    }
  }
}
